finds the change in building in the empty area i.e the empty space in the ROI apart from the initial level of soil that is filled at the very first

In [24]:
import numpy as np
import pandas as pd
import easygui 
import matplotlib.pyplot as plt
import pylab
import matplotlib.ticker as ticker


import plotly.plotly as py
import cufflinks as cf
#%matplotlib inline

In [27]:
dp='/home/subhar/Desktop/data_acquisition/Mound_E/0-60%/new_setup_ completeBlack/2017_08_04'
# path=easygui.fileopenbox(default=dp,filetypes=['*.csv'])

path='/home/subhar/Desktop/data_acquisition/Mound_E/0-60%/new_setup_ completeBlack/2017_08_04/Results.csv'
data_date=path.split('/')[-2]

In [28]:
df=pd.read_csv(path)
df.head()

,,Area1,Mean1,Min1,Max1,%Area1,Area2,Mean2,Min2,Max2,...,Area9,Mean9,Min9,Max9,%Area9,Area10,Mean10,Min10,Max10,%Area10
0,1,36.354,80.763,0,255,31.672,35.636,82.484,0,255,...,38.546,78.219,0,255,30.674,36.824,85.453,0,255,33.511
1,2,36.354,81.564,0,255,31.986,35.636,83.067,0,255,...,0.000,0.000,0,0,0.000,0.000,0.000,0,0,0.000
2,3,36.354,80.563,0,255,31.593,35.636,83.104,0,255,...,0.000,0.000,0,0,0.000,0.000,0.000,0,0,0.000
3,4,36.354,80.896,0,255,31.724,35.636,82.806,0,255,...,0.000,0.000,0,0,0.000,0.000,0.000,0,0,0.000
4,5,36.354,80.052,0,255,31.393,35.636,83.025,0,255,...,0.000,0.000,0,0,0.000,0.000,0.000,0,0,0.000

In [29]:
df1 = df.rename(index=str, columns={"%Area1": "0%","%Area2": "15%","%Area3": "30%","%Area4": "45%","%Area5": "60%"})

df2=df1[['0%','15%','30%','45%','60%']]

df2

         0%     15%     30%     45%     60%
0    31.672  32.347  29.472  30.674  33.511
1    31.986  32.575  29.877  30.706  33.585
2    31.593  32.590  30.070  30.774  33.608
3    31.724  32.473  29.953  30.879  33.581
4    31.393  32.559  30.321  30.748  33.602
5    31.711  32.282  30.314  30.736  33.673
6    31.098  32.574  30.591  30.716  33.655
7    31.629  32.525  31.001  30.713  33.638
8    31.589  32.369  31.070  30.682  33.664
9    31.494  32.330  31.556  30.727  33.643
10   31.476  32.409  31.745  30.677  33.677
11   31.464  32.479  32.276  30.708  33.700
12   31.909  32.204  32.546  30.688  33.651
13   31.538  32.300  32.914  30.702  33.613
14   31.461  32.046  33.282  30.693  33.635
15   31.676  31.963  33.762  30.686  33.685
16   31.205  32.225  34.047  30.773  33.687
17   31.542  32.228  34.197  30.726  33.750
18   31.589  32.099  34.789  30.810  33.737
19   31.505  32.033  35.105  30.742  33.738
20   31.468  32.143  35.520  30.661  33.752
21   31.276  32.107  35.426  30.590  33.701
22   31.564  32.126  36.094  30.563  33.724
23   31.194  32.197  36.452  30.667  33.702
24   31.128  32.280  36.816  30.548  33.664
25   31.457  32.154  37.049  30.748  33.745
26   31.290  32.126  37.488  30.762  33.808
27   31.190  32.156  37.918  30.750  33.808
28   31.232  32.735  38.293  30.751  33.816
29   31.019  32.514  38.458  30.696  33.778
..      ...     ...     ...     ...     ...
170  30.669  32.319  62.615  35.664  33.836
171  30.654  32.391  62.617  35.522  33.859
172  30.603  32.439  62.699  35.576  33.850
173  30.594  32.413  62.708  35.634  33.827
174  30.571  32.393  62.692  35.689  33.830
175  30.547  32.187  62.723  35.754  33.824
176  30.563  32.273  62.744  35.881  33.827
177  30.553  32.412  62.874  35.801  33.826
178  30.967  32.248  62.773  35.841  33.795
179  30.720  32.384  62.895  35.871  33.830
180  30.658  32.292  62.794  35.801  33.832
181  30.761  32.246  62.830  35.812  33.815
182  30.613  32.303  62.828  35.820  33.827
183  30.626  32.338  62.919  35.795  33.822
184  30.700  32.435  63.078  35.847  33.829
185  30.530  32.502  63.046  35.847  33.861
186  30.511  32.397  63.068  35.828  33.867
187  30.575  32.485  63.123  35.873  33.876
188  30.522  32.437  63.045  35.901  33.882
189  30.500  32.469  63.045  35.888  33.863
190  30.500  32.465  63.064  35.917  33.866
191  30.541  32.389  63.090  35.878  33.896
192  30.502  32.417  63.098  35.919  33.912
193  30.484  32.267  63.224  35.967  33.892
194  30.547  32.320  63.267  36.022  33.877
195  30.499  32.193  63.261  36.022  33.858
196  30.555  32.281  63.271  36.027  33.879
197  30.528  32.273  63.226  36.169  33.862
198  30.486  32.435  63.206  36.265  33.837
199  30.501  32.424  63.233  36.258  33.878

[200 rows x 5 columns]

In [12]:
#a=df2.plot()
#plt.yscale("linear")

In [21]:
print path

/home/subhar/Desktop/data_acquisition/Mound_E/0-60%/new_setup_ completeBlack/2017_08_04/Results2017_08_04 change.csv

In [23]:
a=df2.plot(figsize=(8,6))
#a.scale_x=20
#a.scale_y=2
#pylab.ylim([20,70])
#pylab.xlim([0,200])
#plt.xticks(np.arange(0,200,5.0))
#ticks_x = ticker.FuncFormatter(5)
#a.xaxis.set_major_formatter(ticks_x)
#tick_spacing=20
#tick_spacing1=5
#a.xaxis.set_major_locator(ticker.LinearLocator(10))
plt.xticks(range(0,200,20), range(0,200,20))

#a.xaxis.set_major_locator(ticker.MultipleLocator(tick_spacing))
#a.yaxis.set_major_locator(ticker.MultipleLocator(tick_spacing1))
#plt.yscale('linear')
#plt.xscale('linear')

a.set_xlabel("Time (mins)")
a.set_ylabel("Area fraction built (percentage)")
a.set_title(data_date)
plt.savefig(data_date+'.png',dpi=300)
# plt.show()

In [30]:
sns.set(style="darkgrid", color_codes=True)

a=df2.plot(figsize=(10,10))
max_xticks = 6
max_yticks = 8

xloc = plt.MaxNLocator(max_xticks)
yloc = plt.MaxNLocator(max_yticks)

a.xaxis.set_major_locator(xloc)
a.yaxis.set_major_locator(yloc)

NameError: name 'sns' is not defined

In [31]:
a.savefig('2017_07_06'+'.png',dpi=300)#savefigure

AttributeError: 'AxesSubplot' object has no attribute 'savefig'

In [44]:
df2.iplot(kind='scatter')
a.set_xlabel("Time (mins)")
a.set_ylabel("Area fraction built (percentage)")

In [ ]:
df2